packages:
  - apps/*
  - packages/*

overrides:
  '@prisma/config@6.19.2>effect': 3.20.0

allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  esbuild: true
  msgpackr-extract: false
  prisma: true
